AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Parameters:
  AuthBaseUrl:
    Type: String
  DatabaseUrl:
    Type: String
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prod
  JwtSecret:
    Type: String
  MailHost:
    Type: String
  MailPassword:
    Type: String
  MailPort:
    Type: String
  MailUsername:
    Type: String

Globals:
  Function:
    Timeout: 30
    MemorySize: 128
    Runtime: nodejs22.x
    Architectures:
      - arm64

Resources:
  AuthApi:
    Type: AWS::Serverless::Api
    Properties:
      OpenApiVersion: "2.0"
      StageName: !Ref Environment
      Cors:
        AllowMethods: "'*'"
        AllowHeaders: "'*'"
        AllowOrigin: "'*'"
      EndpointConfiguration: REGIONAL
      Auth:
        DefaultAuthorizer: NONE
      DisableExecuteApiEndpoint: false
      TracingEnabled: false
      Variables:
        Port: 8001

  RequestEmailOtpFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: request-email-otp
      Handler: index.handler
      Layers:
        - !Sub arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:layer:prisma:1
      Policies:
        - AWSLambdaBasicExecutionRole
        - Statement:
            - Sid: LayerAccess
              Effect: Allow
              Action:
                - lambda:GetLayerVersion
              Resource: !Sub arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:layer:prisma:1
      Events:
        ApiEvent:
          Type: Api
          Properties:
            RestApiId: !Ref AuthApi
            Path: /auth/otp/request/email
            Method: post
      Environment:
        Variables:
          DATABASE_URL: !Ref DatabaseUrl
          MAIL_HOST: !Ref MailHost
          MAIL_PASSWORD: !Ref MailPassword
          MAIL_PORT: !Ref MailPort
          MAIL_USERNAME: !Ref MailUsername
          PRISMA_QUERY_ENGINE_LIBRARY: /opt/nodejs/node_modules/.prisma/client/libquery_engine-linux-arm64-openssl-3.0.x.so.node
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Bundle: true
        KeepNames: false
        Minify: true
        Sourcemap: false
        Target: "node22"
        TreeShaking: true

  RequestMagicLinkFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: request-magic-link
      Handler: index.handler
      Policies:
        - AWSLambdaBasicExecutionRole
      Events:
        ApiEvent:
          Type: Api
          Properties:
            RestApiId: !Ref AuthApi
            Path: /auth/magic-link/request
            Method: post
      Environment:
        Variables:
          AUTH_BASE_URL: !Ref AuthBaseUrl
          JWT_SECRET: !Ref JwtSecret
          MAIL_HOST: !Ref MailHost
          MAIL_PASSWORD: !Ref MailPassword
          MAIL_PORT: !Ref MailPort
          MAIL_USERNAME: !Ref MailUsername
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Bundle: true
        KeepNames: false
        Minify: true
        Sourcemap: false
        Target: "node22"
        TreeShaking: true

  VerifyOtpFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: verify-otp
      Handler: index.handler
      Layers:
        - !Sub arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:layer:prisma:1
      Policies:
        - AWSLambdaBasicExecutionRole
        - Statement:
            - Sid: LayerAccess
              Effect: Allow
              Action:
                - lambda:GetLayerVersion
              Resource: !Sub arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:layer:prisma:1
      Events:
        ApiEvent:
          Type: Api
          Properties:
            RestApiId: !Ref AuthApi
            Path: /auth/otp/verify
            Method: get
      Environment:
        Variables:
          DATABASE_URL: !Ref DatabaseUrl
          JWT_SECRET: !Ref JwtSecret
          PRISMA_QUERY_ENGINE_LIBRARY: /opt/nodejs/node_modules/.prisma/client/libquery_engine-linux-arm64-openssl-3.0.x.so.node
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Bundle: true
        KeepNames: false
        Minify: true
        Sourcemap: false
        Target: "node22"
        TreeShaking: true

  VerifyMagicLinkFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: verify-magic-link
      Handler: index.handler
      Layers:
        - !Sub arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:layer:prisma:1
      Policies:
        - AWSLambdaBasicExecutionRole
        - Statement:
            - Sid: LayerAccess
              Effect: Allow
              Action:
                - lambda:GetLayerVersion
              Resource: !Sub arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:layer:prisma:1
      Events:
        ApiEvent:
          Type: Api
          Properties:
            RestApiId: !Ref AuthApi
            Path: /auth/magic-link/verify
            Method: get
      Environment:
        Variables:
          DATABASE_URL: !Ref DatabaseUrl
          JWT_SECRET: !Ref JwtSecret
          PRISMA_QUERY_ENGINE_LIBRARY: /opt/nodejs/node_modules/.prisma/client/libquery_engine-linux-arm64-openssl-3.0.x.so.node
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Bundle: true
        KeepNames: false
        Minify: true
        Sourcemap: false
        Target: "node22"
        TreeShaking: true

Outputs:
  AuthApiEndpoint:
    Value: !Sub "https://${AuthApi}.execute-api.${AWS::Region}.amazonaws.com/${Environment}/"
