AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Parameters:
  DatabaseUrl:
    Type: String
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prod

Globals:
  Function:
    Timeout: 30
    MemorySize: 128
    Runtime: nodejs22.x
    Architectures:
      - arm64

Resources:
  CoursesApi:
    Type: AWS::Serverless::Api
    Properties:
      OpenApiVersion: "2.0"
      StageName: !Ref Environment
      Cors:
        AllowMethods: "'*'"
        AllowHeaders: "'*'"
        AllowOrigin: "'*'"
      EndpointConfiguration: REGIONAL
      Auth:
        DefaultAuthorizer: JwtAuthorizer
        Authorizers:
          JwtAuthorizer:
            FunctionArn: !Sub arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:JwtAuthorizerFunction
            Identity:
              Header: Authorization
            AuthorizerResultTtlInSeconds: 0
      DisableExecuteApiEndpoint: false
      TracingEnabled: false
      Variables:
        Port: 8005

  CoursesApiGatewayInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Sub arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:JwtAuthorizerFunction
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${CoursesApi}/*"

  CreateCoursesFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: create-courses
      Handler: index.handler
      Layers:
        - !Sub arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:layer:prisma:5
      Policies:
        - AWSLambdaBasicExecutionRole
        - Statement:
            - Sid: LayerAccess
              Effect: Allow
              Action:
                - lambda:GetLayerVersion
              Resource: !Sub arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:layer:prisma:5
      Events:
        ApiEvent:
          Type: Api
          Properties:
            RestApiId: !Ref CoursesApi
            Path: /courses
            Method: post
      Environment:
        Variables:
          DATABASE_URL: !Ref DatabaseUrl
          PRISMA_QUERY_ENGINE_LIBRARY: /opt/nodejs/node_modules/.prisma/client/libquery_engine-linux-arm64-openssl-3.0.x.so.node
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Bundle: true
        KeepNames: false
        Minify: true
        Sourcemap: false
        Target: "node22"
        TreeShaking: true

  RecommendCoursesFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: recommend-courses
      Handler: index.handler
      Layers:
        - !Sub arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:layer:prisma:5
      Policies:
        - AWSLambdaBasicExecutionRole
        - Statement:
            - Sid: LayerAccess
              Effect: Allow
              Action:
                - lambda:GetLayerVersion
              Resource: !Sub arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:layer:prisma:5
      Events:
        ApiEvent:
          Type: Api
          Properties:
            RestApiId: !Ref CoursesApi
            Path: /courses/recommendation
            Method: get
      Environment:
        Variables:
          DATABASE_URL: !Ref DatabaseUrl
          PRISMA_QUERY_ENGINE_LIBRARY: /opt/nodejs/node_modules/.prisma/client/libquery_engine-linux-arm64-openssl-3.0.x.so.node
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Bundle: true
        KeepNames: false
        Minify: true
        Sourcemap: false
        Target: "node22"
        TreeShaking: true

  RecommendCoursesByGoalsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: recommend-courses-by-goals
      Handler: index.handler
      Layers:
        - !Sub arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:layer:prisma:5
      Policies:
        - AWSLambdaBasicExecutionRole
        - Statement:
            - Sid: LayerAccess
              Effect: Allow
              Action:
                - lambda:GetLayerVersion
              Resource: !Sub arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:layer:prisma:5
      Events:
        ApiEvent:
          Type: Api
          Properties:
            RestApiId: !Ref CoursesApi
            Path: /courses/recommendation/goals
            Method: get
      Environment:
        Variables:
          DATABASE_URL: !Ref DatabaseUrl
          PRISMA_QUERY_ENGINE_LIBRARY: /opt/nodejs/node_modules/.prisma/client/libquery_engine-linux-arm64-openssl-3.0.x.so.node
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Bundle: true
        KeepNames: false
        Minify: true
        Sourcemap: false
        Target: "node22"
        TreeShaking: true

  SearchCoursesFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: search-courses
      Handler: index.handler
      Layers:
        - !Sub arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:layer:prisma:5
      Policies:
        - AWSLambdaBasicExecutionRole
        - Statement:
            - Sid: LayerAccess
              Effect: Allow
              Action:
                - lambda:GetLayerVersion
              Resource: !Sub arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:layer:prisma:5
      Events:
        ApiEvent:
          Type: Api
          Properties:
            RestApiId: !Ref CoursesApi
            Path: /courses/search
            Method: get
      Environment:
        Variables:
          DATABASE_URL: !Ref DatabaseUrl
          PRISMA_QUERY_ENGINE_LIBRARY: /opt/nodejs/node_modules/.prisma/client/libquery_engine-linux-arm64-openssl-3.0.x.so.node
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Bundle: true
        KeepNames: false
        Minify: true
        Sourcemap: false
        Target: "node22"
        TreeShaking: true

Outputs:
  CoursesApiEndpoint:
    Value: !Sub "https://${CoursesApi}.execute-api.${AWS::Region}.amazonaws.com/${Environment}/"
