service: careercanvas-auth

provider:
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
  environment:
    NODE_ENV: ${self:provider.stage}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${self:provider.region}:*:table/*"
    - Effect: Allow
      Action:
        - ses:SendEmail
        - ses:SendRawEmail
      Resource: "*"
    - Effect: Allow
      Action:
        - sns:Publish
      Resource: "*"

functions:
  authenticate:
    handler: src/handlers/auth.authenticate
    events:
      - http:
          path: /auth/login
          method: post
          cors: true

  register:
    handler: src/handlers/auth.register
    events:
      - http:
          path: /auth/register
          method: post
          cors: true

  verifyEmail:
    handler: src/handlers/auth.verifyEmail
    events:
      - http:
          path: /auth/verify-email
          method: post
          cors: true

  resetPassword:
    handler: src/handlers/auth.resetPassword
    events:
      - http:
          path: /auth/reset-password
          method: post
          cors: true

resources:
  Resources:
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.stage}-users
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: email
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: email-index
            KeySchema:
              - AttributeName: email
                KeyType: HASH
            Projection:
              ProjectionType: ALL
        BillingMode: PAY_PER_REQUEST

plugins:
  - serverless-offline
  - serverless-dotenv-plugin

package:
  patterns:
    - '!node_modules/.prisma/**'
    - '!node_modules/@prisma/**'
    - '!tests/**'
    - '!coverage/**'
    - '!.env*'
    - '!tsconfig.json'
    - '!README.md'