AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Parameters:
  DatabaseUrl:
    Type: String
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prod
  S3Bucket:
    Type: String

Globals:
  Function:
    Timeout: 30
    MemorySize: 128
    Runtime: nodejs22.x
    Architectures:
      - arm64

Resources:
  ResumesApi:
    Type: AWS::Serverless::Api
    Properties:
      OpenApiVersion: "2.0"
      StageName: !Ref Environment
      BinaryMediaTypes:
        - application/pdf
      Cors:
        AllowMethods: "'*'"
        AllowHeaders: "'*'"
        AllowOrigin: "'*'"
      EndpointConfiguration: REGIONAL
      Auth:
        DefaultAuthorizer: JwtAuthorizer
        Authorizers:
          JwtAuthorizer:
            FunctionArn: !Sub arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:JwtAuthorizerFunction
            Identity:
              Header: Authorization
            AuthorizerResultTtlInSeconds: 0
      DisableExecuteApiEndpoint: false
      TracingEnabled: false

  ResumesApiGatewayInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Sub arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:JwtAuthorizerFunction
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${ResumesApi}/*"

  BuildCustomResumeFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: build-custom-resume
      Handler: index.handler
      Layers:
        - !Sub arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:layer:prisma:3
      Policies:
        - AWSLambdaBasicExecutionRole
        - Statement:
            - Sid: LayerAccess
              Effect: Allow
              Action:
                - lambda:GetLayerVersion
              Resource: !Sub arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:layer:prisma:3
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - s3:PutObject
                - s3:PutObjectAcl
              Resource:
                - !Sub "arn:aws:s3:::${S3Bucket}/*"
      Events:
        ApiEvent:
          Type: Api
          Properties:
            RestApiId: !Ref ResumesApi
            Path: /resumes
            Method: post
      Environment:
        Variables:
          DATABASE_URL: !Ref DatabaseUrl
          PRISMA_QUERY_ENGINE_LIBRARY: /opt/nodejs/node_modules/.prisma/client/libquery_engine-linux-arm64-openssl-3.0.x.so.node
          REGION: !Ref AWS::Region
          S3_BUCKET: !Ref S3Bucket
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Bundle: true
        KeepNames: false
        Minify: true
        Sourcemap: false
        Target: "node22"
        TreeShaking: true

  DeleteCustomResumeFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: delete-custom-resume
      Handler: index.handler
      Layers:
        - !Sub arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:layer:prisma:1
      Policies:
        - AWSLambdaBasicExecutionRole
        - Statement:
            - Sid: LayerAccess
              Effect: Allow
              Action:
                - lambda:GetLayerVersion
              Resource: !Sub arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:layer:prisma:1
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - s3:DeleteObject
              Resource:
                - !Sub "arn:aws:s3:::${S3Bucket}/*"
      Events:
        ApiEvent:
          Type: Api
          Properties:
            RestApiId: !Ref ResumesApi
            Path: /resumes/{resumeId}
            Method: delete
      Environment:
        Variables:
          DATABASE_URL: !Ref DatabaseUrl
          PRISMA_QUERY_ENGINE_LIBRARY: /opt/nodejs/node_modules/.prisma/client/libquery_engine-linux-arm64-openssl-3.0.x.so.node
          REGION: !Ref AWS::Region
          S3_BUCKET: !Ref S3Bucket
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Bundle: true
        KeepNames: false
        Minify: true
        Sourcemap: false
        Target: "node22"
        TreeShaking: true

Outputs:
  ResumesApiEndpoint:
    Value: !Sub "https://${ResumesApi}.execute-api.${AWS::Region}.amazonaws.com/${Environment}/"
