AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Parameters:
  DatabaseUrl:
    Type: String
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prod
  HashSecret:
    Type: String

Globals:
  Function:
    Timeout: 30
    MemorySize: 128
    Runtime: nodejs22.x
    Architectures:
      - arm64

Resources:
  IntegrationsApi:
    Type: AWS::Serverless::Api
    Properties:
      OpenApiVersion: "2.0"
      StageName: !Ref Environment
      Cors:
        AllowMethods: "'*'"
        AllowHeaders: "'*'"
        AllowOrigin: "'*'"
      EndpointConfiguration: REGIONAL
      Auth:
        DefaultAuthorizer: AdminJwtAuthorizer
        Authorizers:
          AdminJwtAuthorizer:
            FunctionArn: !Sub arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:AdminJwtAuthorizerFunction
            Identity:
              Header: Authorization
            AuthorizerResultTtlInSeconds: 0
      DisableExecuteApiEndpoint: false
      TracingEnabled: false

  IntegrationsApiGatewayInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Sub arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:AdminJwtAuthorizerFunction
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${IntegrationsApi}/*"

  CreateApiKeyFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: create-api-key
      Handler: index.handler
      Layers:
        - !Sub arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:layer:prisma:1
      Policies:
        - AWSLambdaBasicExecutionRole
        - Statement:
            - Sid: LayerAccess
              Effect: Allow
              Action:
                - lambda:GetLayerVersion
              Resource: !Sub arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:layer:prisma:1
      Events:
        ApiEvent:
          Type: Api
          Properties:
            RestApiId: !Ref IntegrationsApi
            Path: /integrations/{integrationId}/api-keys
            Method: post
      Environment:
        Variables:
          DATABASE_URL: !Ref DatabaseUrl
          HASH_SECRET: !Ref HashSecret
          PRISMA_QUERY_ENGINE_LIBRARY: /opt/nodejs/node_modules/.prisma/client/libquery_engine-linux-arm64-openssl-3.0.x.so.node
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Bundle: true
        KeepNames: false
        Minify: true
        Sourcemap: false
        Target: "node22"
        TreeShaking: true

  CreateIntegrationFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: create-integration
      Handler: index.handler
      Layers:
        - !Sub arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:layer:prisma:1
      Policies:
        - AWSLambdaBasicExecutionRole
        - Statement:
            - Sid: LayerAccess
              Effect: Allow
              Action:
                - lambda:GetLayerVersion
              Resource: !Sub arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:layer:prisma:1
      Events:
        ApiEvent:
          Type: Api
          Properties:
            RestApiId: !Ref IntegrationsApi
            Path: /integrations
            Method: post
      Environment:
        Variables:
          DATABASE_URL: !Ref DatabaseUrl
          PRISMA_QUERY_ENGINE_LIBRARY: /opt/nodejs/node_modules/.prisma/client/libquery_engine-linux-arm64-openssl-3.0.x.so.node
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Bundle: true
        KeepNames: false
        Minify: true
        Sourcemap: false
        Target: "node22"
        TreeShaking: true

  DeleteApiKeyFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: delete-api-key
      Handler: index.handler
      Layers:
        - !Sub arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:layer:prisma:1
      Policies:
        - AWSLambdaBasicExecutionRole
        - Statement:
            - Sid: LayerAccess
              Effect: Allow
              Action:
                - lambda:GetLayerVersion
              Resource: !Sub arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:layer:prisma:1
      Events:
        ApiEvent:
          Type: Api
          Properties:
            RestApiId: !Ref IntegrationsApi
            Path: /integrations/api-keys/{apiKeyId}
            Method: delete
      Environment:
        Variables:
          DATABASE_URL: !Ref DatabaseUrl
          PRISMA_QUERY_ENGINE_LIBRARY: /opt/nodejs/node_modules/.prisma/client/libquery_engine-linux-arm64-openssl-3.0.x.so.node
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Bundle: true
        KeepNames: false
        Minify: true
        Sourcemap: false
        Target: "node22"
        TreeShaking: true

  FindApiKeysFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: find-api-keys
      Handler: index.handler
      Layers:
        - !Sub arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:layer:prisma:1
      Policies:
        - AWSLambdaBasicExecutionRole
        - Statement:
            - Sid: LayerAccess
              Effect: Allow
              Action:
                - lambda:GetLayerVersion
              Resource: !Sub arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:layer:prisma:1
      Events:
        ApiEvent:
          Type: Api
          Properties:
            RestApiId: !Ref IntegrationsApi
            Path: /integrations/{integrationId}/api-keys
            Method: get
      Environment:
        Variables:
          DATABASE_URL: !Ref DatabaseUrl
          PRISMA_QUERY_ENGINE_LIBRARY: /opt/nodejs/node_modules/.prisma/client/libquery_engine-linux-arm64-openssl-3.0.x.so.node
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Bundle: true
        KeepNames: false
        Minify: true
        Sourcemap: false
        Target: "node22"
        TreeShaking: true

  FindIntegrationFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: find-integration
      Handler: index.handler
      Layers:
        - !Sub arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:layer:prisma:1
      Policies:
        - AWSLambdaBasicExecutionRole
        - Statement:
            - Sid: LayerAccess
              Effect: Allow
              Action:
                - lambda:GetLayerVersion
              Resource: !Sub arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:layer:prisma:1
      Events:
        ApiEvent:
          Type: Api
          Properties:
            RestApiId: !Ref IntegrationsApi
            Path: /integrations/{integrationId}
            Method: get
      Environment:
        Variables:
          DATABASE_URL: !Ref DatabaseUrl
          PRISMA_QUERY_ENGINE_LIBRARY: /opt/nodejs/node_modules/.prisma/client/libquery_engine-linux-arm64-openssl-3.0.x.so.node
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Bundle: true
        KeepNames: false
        Minify: true
        Sourcemap: false
        Target: "node22"
        TreeShaking: true

  FindIntegrationsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: find-integrations
      Handler: index.handler
      Layers:
        - !Sub arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:layer:prisma:1
      Policies:
        - AWSLambdaBasicExecutionRole
        - Statement:
            - Sid: LayerAccess
              Effect: Allow
              Action:
                - lambda:GetLayerVersion
              Resource: !Sub arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:layer:prisma:1
      Events:
        ApiEvent:
          Type: Api
          Properties:
            RestApiId: !Ref IntegrationsApi
            Path: /integrations
            Method: get
      Environment:
        Variables:
          DATABASE_URL: !Ref DatabaseUrl
          PRISMA_QUERY_ENGINE_LIBRARY: /opt/nodejs/node_modules/.prisma/client/libquery_engine-linux-arm64-openssl-3.0.x.so.node
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Bundle: true
        KeepNames: false
        Minify: true
        Sourcemap: false
        Target: "node22"
        TreeShaking: true

  UpdateApiKeyStatusFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: update-api-key-status
      Handler: index.handler
      Layers:
        - !Sub arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:layer:prisma:1
      Policies:
        - AWSLambdaBasicExecutionRole
        - Statement:
            - Sid: LayerAccess
              Effect: Allow
              Action:
                - lambda:GetLayerVersion
              Resource: !Sub arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:layer:prisma:1
      Events:
        ApiEvent:
          Type: Api
          Properties:
            RestApiId: !Ref IntegrationsApi
            Path: /integrations/api-keys/{apiKeyId}
            Method: patch
      Environment:
        Variables:
          DATABASE_URL: !Ref DatabaseUrl
          PRISMA_QUERY_ENGINE_LIBRARY: /opt/nodejs/node_modules/.prisma/client/libquery_engine-linux-arm64-openssl-3.0.x.so.node
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Bundle: true
        KeepNames: false
        Minify: true
        Sourcemap: false
        Target: "node22"
        TreeShaking: true

  UpdateIntegrationFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: update-integration
      Handler: index.handler
      Layers:
        - !Sub arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:layer:prisma:1
      Policies:
        - AWSLambdaBasicExecutionRole
        - Statement:
            - Sid: LayerAccess
              Effect: Allow
              Action:
                - lambda:GetLayerVersion
              Resource: !Sub arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:layer:prisma:1
      Events:
        ApiEvent:
          Type: Api
          Properties:
            RestApiId: !Ref IntegrationsApi
            Path: /integrations/{integrationId}
            Method: patch
      Environment:
        Variables:
          DATABASE_URL: !Ref DatabaseUrl
          PRISMA_QUERY_ENGINE_LIBRARY: /opt/nodejs/node_modules/.prisma/client/libquery_engine-linux-arm64-openssl-3.0.x.so.node
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Bundle: true
        KeepNames: false
        Minify: true
        Sourcemap: false
        Target: "node22"
        TreeShaking: true

  ValidateApiKeyFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: validate-api-key
      Handler: index.handler
      Layers:
        - !Sub arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:layer:prisma:1
      Policies:
        - AWSLambdaBasicExecutionRole
        - Statement:
            - Sid: LayerAccess
              Effect: Allow
              Action:
                - lambda:GetLayerVersion
              Resource: !Sub arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:layer:prisma:1
      Events:
        ApiEvent:
          Type: Api
          Properties:
            RestApiId: !Ref IntegrationsApi
            Path: /integrations/api-keys/validate
            Method: post
            Auth:
              Authorizer: NONE
      Environment:
        Variables:
          DATABASE_URL: !Ref DatabaseUrl
          HASH_SECRET: !Ref HashSecret
          PRISMA_QUERY_ENGINE_LIBRARY: /opt/nodejs/node_modules/.prisma/client/libquery_engine-linux-arm64-openssl-3.0.x.so.node
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Bundle: true
        KeepNames: false
        Minify: true
        Sourcemap: false
        Target: "node22"
        TreeShaking: true

Outputs:
  IntegrationsApiEndpoint:
    Value: !Sub "https://${IntegrationsApi}.execute-api.${AWS::Region}.amazonaws.com/${Environment}/"
