name: CareerCanvas API CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18.x'
    
    - name: Install Dependencies
      run: |
        npm install
        npm install -g lerna
        npm install -ws
    
    - name: Build
      run: lerna run build
    
  deploy:
    needs: build
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: production
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Deploy to EC2
      uses: appleboy/ssh-action@v1.0.0
      env:
        AWSREGION_PRODUCTION: ${{ secrets.AWSREGION_PRODUCTION }}
        CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
      with:
        host: ${{ secrets.EC2_HOST }}
        username: deploy
        key: ${{ secrets.DEPLOY_SSH_KEY }}
        port: 22
        command_timeout: "30m"
        script_stop: true
        envs: |
          REPO_ACCESS_TOKEN=${{ secrets.REPO_ACCESS_TOKEN }}
          AWSREGION_PRODUCTION
          CLIENT_SECRET
        script: |
          # Set environment variables explicitly
          echo "export AWSREGION_PRODUCTION='${AWSREGION_PRODUCTION}'" >> ~/.bashrc
          echo "export CLIENT_SECRET='${CLIENT_SECRET}'" >> ~/.bashrc
          source ~/.bashrc
          
          # Install Node.js using NVM
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
          nvm use 18 || nvm install 18
          
          # Install global packages
          npm install -g lerna pm2
          
          # Stop existing PM2 processes
          pm2 kill || true
          
          # Setup project directory
          rm -rf /home/deploy/CareerCanvas.Api
          mkdir -p /home/deploy/CareerCanvas.Api
          cd /home/deploy/CareerCanvas.Api
          
          # Clone repository with token
          git clone "https://oauth2:${REPO_ACCESS_TOKEN}@github.com/CareerCanvasPro/CareerCanvas.Api.git" .
          git config --global --add safe.directory /home/deploy/CareerCanvas.Api
          
          # Install project dependencies
          if [ -f "package.json" ]; then
              npm install
              npm install -ws
              lerna run build
              
              # Deploy services
              bash deployment/scripts/deploy.sh
          else
              echo "Error: package.json not found"
              exit 1
          fi