name: CareerCanvas API CI/CD

on:
  push:
    paths:
      - 'services/**'
      - 'utility/**'
      - 'packages/**'
    branches: [main, dev]
  pull_request:
    paths:
      - 'services/**'
      - 'utility/**'
      - 'packages/**'
    branches: [main, dev]

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.ref == 'refs/heads/main' && 'production' || 'development' }}
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Configure SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.DEPLOY_SSH_KEY }}
          
      - name: Deploy to EC2
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USER: deploy
          AWS_REGION: ${{ github.ref == 'refs/heads/main' && secrets.AWSREGION_PRODUCTION || secrets.AWS_REGION }}
        run: |
          ssh -o StrictHostKeyChecking=no $EC2_USER@$EC2_HOST << 'EOF'
            cd /home/deploy/CareerCanvas.Api
            git fetch
            git checkout ${{ github.ref_name }}
            git pull
            npm install
            for d in services/*/ ; do
              cd "$d"
              npm install
              npm run build
              pm2 restart $(basename "$d")-service || pm2 start npm --name "$(basename "$d")-service" -- start
              cd ../../
            done
            pm2 save
          EOF

      - name: Notify Deployment
        if: success()
        uses: slackapi/slack-github-action@v1.24.0
        with:
          channel-id: 'deployments'
          slack-message: '🚀 Services deployed to ${{ github.ref == "refs/heads/main" && "production" || "development" }} successfully!'
        env:
          SLACK_BOT_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}