name: CareerCanvas API CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18.x"

      - name: Install Dependencies
        run: |
          npm install
          npm install -g lerna rimraf
          npm install -ws
          npm shrinkwrap

      - name: Build
        run: |
          lerna bootstrap
          lerna run build

      - name: Cache Build
        uses: actions/cache@v3
        with:
          path: |
            **/lib
            **/node_modules
            npm-shrinkwrap.json
          key: ${{ runner.os }}-build-${{ github.sha }}

  deploy:
    needs: build
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v4

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.0
        env:
          DEPLOY_ENV: |
            AWSREGION_PRODUCTION='${{ secrets.AWSREGION_PRODUCTION }}'
            CLIENT_SECRET='${{ secrets.CLIENT_SECRET }}'
            PM2_AWSREGION_PRODUCTION='${{ secrets.AWSREGION_PRODUCTION }}'
            PM2_CLIENT_SECRET='${{ secrets.CLIENT_SECRET }}'
        with:
          host: ${{ secrets.EC2_HOST }}
          username: deploy
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          port: 22
          command_timeout: "30m"
          script_stop: true
          script: |
            DEPLOY_DIR="/home/deploy/CareerCanvas.Api"
            REPO_URL="https://oauth2:${{ secrets.REPO_ACCESS_TOKEN }}@github.com/CareerCanvasPro/CareerCanvas.Api.git"

            # Update environment file
            echo "$DEPLOY_ENV" > ~/.env
            set -a; source ~/.env; set +a

            # Setup Node.js
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            nvm use 18 || nvm install 18

            # Install global packages
            npm install -g lerna pm2 rimraf

            # Stop existing services
            pm2 delete all || true

            # Clean up existing directory with force
            cd /home/deploy
            rm -rf CareerCanvas.Api
            
            # Clone fresh repository
            git clone "https://oauth2:${GH_TOKEN}@github.com/CareerCanvasPro/CareerCanvas.Api.git"
            cd CareerCanvas.Api

            # Copy environment file
            cp ~/.env .env

            # Clean and rebuild
            npm ci
            npm install -ws
            lerna clean -y --yes
            lerna bootstrap
            lerna run build

            # Set PM2_HOME and deploy
            export PM2_HOME=/home/deploy/.pm2
            bash deployment/scripts/deploy.sh