name: CareerCanvas API CI/CD

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
    
    - name: Install Dependencies
      run: |
        npm install
        npm install -g lerna
        npm install -ws
    
    - name: Build
      run: lerna run build
    
    # Temporarily comment out tests until they're configured
    # - name: Test
    #   run: lerna run test
    
  deploy:
    needs: build
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    
    steps:
    - name: Setup SSH Keys
      run: |
        mkdir -p /home/runner/.ssh/
        echo "${{ secrets.DEPLOY_SSH_KEY }}" > /home/runner/.ssh/deploy_key
        chmod 600 /home/runner/.ssh/deploy_key
        
    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: deploy
        key_path: /home/runner/.ssh/deploy_key
        port: 22
        envs: REPO_ACCESS_TOKEN=${{ secrets.REPO_ACCESS_TOKEN }}
        script: |
          # Install Node.js using NVM
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
          nvm use 18 || nvm install 18
          
          # Install global packages
          npm install -g lerna pm2
          
          # Setup project directory
          rm -rf /home/deploy/CareerCanvas.Api
          mkdir -p /home/deploy/CareerCanvas.Api
          cd /home/deploy/CareerCanvas.Api
          
          # Clone repository with token
          git clone "https://oauth2:${REPO_ACCESS_TOKEN}@github.com/CareerCanvasPro/CareerCanvas.Api.git" .
          git config --global --add safe.directory /home/deploy/CareerCanvas.Api
          
          # Verify clone and directory contents
          ls -la
          cat package.json || echo "package.json not found"
          
          # Install project dependencies only if package.json exists
          if [ -f "package.json" ]; then
            npm install
            npm install -ws
            lerna run build
            bash deploy.sh
          else
            echo "Error: package.json not found"
            exit 1
          fi