service: careercanvas-course-management

provider:
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
  environment:
    NODE_ENV: ${self:provider.stage}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${self:provider.region}:*:table/*"

functions:
  createCourse:
    handler: src/handlers/course.create
    events:
      - http:
          path: /courses
          method: post
          cors: true
          authorizer: aws_iam

  getCourse:
    handler: src/handlers/course.get
    events:
      - http:
          path: /courses/{id}
          method: get
          cors: true

  listCourses:
    handler: src/handlers/course.list
    events:
      - http:
          path: /courses
          method: get
          cors: true

  updateCourse:
    handler: src/handlers/course.update
    events:
      - http:
          path: /courses/{id}
          method: put
          cors: true
          authorizer: aws_iam

  deleteCourse:
    handler: src/handlers/course.delete
    events:
      - http:
          path: /courses/{id}
          method: delete
          cors: true
          authorizer: aws_iam

resources:
  Resources:
    CoursesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.stage}-courses
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: creatorId
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: creatorId-index
            KeySchema:
              - AttributeName: creatorId
                KeyType: HASH
            Projection:
              ProjectionType: ALL
        BillingMode: PAY_PER_REQUEST

plugins:
  - serverless-offline
  - serverless-dotenv-plugin

package:
  patterns:
    - '!node_modules/.prisma/**'
    - '!node_modules/@prisma/**'
    - '!tests/**'
    - '!coverage/**'
    - '!.env*'
    - '!tsconfig.json'
    - '!README.md'